<?xml version="1.0" encoding="UTF-8"?>

<message CommandCode="272" request="1">
   <Destination-Realm mandatory="1">emblacom.com</Destination-Realm>
   <Auth-Application-Id mandatory="1">4</Auth-Application-Id>
   <Service-Context-Id mandatory="1">32251@3gpp.org</Service-Context-Id>
   <CC-Request-Type mandatory="1">1</CC-Request-Type>
   <CC-Request-Number mandatory="1">0</CC-Request-Number>
   <Origin-State-Id mandatory="1">1348041829</Origin-State-Id>
   <Event-Timestamp mandatory="1"/>
   <Subscription-Id mandatory="1">
      <Subscription-Id-Type mandatory="1">48790965042</Subscription-Id-Type>
      <Subscription-Id-Data mandatory="1">260980003000042</Subscription-Id-Data>
   </Subscription-Id>
   <Multiple-Services-Indicator mandatory="1">1</Multiple-Services-Indicator>
   <Multiple-Services-Credit-Control mandatory="1">
      <Requested-Service-Unit mandatory="1"/>
      <Rating-Group mandatory="1">1</Rating-Group>
   </Multiple-Services-Credit-Control>
   <Service-Information mandatory="1">
      <PS-Information mandatory="1">
         <G3PP-Charging-Id mandatory="1">33554660</G3PP-Charging-Id>
         <G3PP-PDP-Type mandatory="1">0</G3PP-PDP-Type>
         <PDP-Address mandatory="1">10.11.100.49</PDP-Address>
         <G3PP-GPRS-Negotiated-QoS-Profile mandatory="1">99-13921f73966897442a6868</G3PP-GPRS-Negotiated-QoS-Profile>
         <SGSN-Address mandatory="1">89.108.192.57</SGSN-Address>
         <GGSN-Address mandatory="1">89.108.192.53</GGSN-Address>
         <CG-Address mandatory="1"></CG-Address>
         <G3PP-IMSI-MCC-MNC mandatory="1">26006</G3PP-IMSI-MCC-MNC>
         <G3PP-GGSN-MCC-MNC mandatory="1">26006</G3PP-GGSN-MCC-MNC>
         <G3PP-NSAPI mandatory="1">5</G3PP-NSAPI>
         <Called-Station-Id mandatory="1">internet</Called-Station-Id>
         <G3PP-Selection-Mode mandatory="1">0</G3PP-Selection-Mode>
         <G3PP-Charging-Characteristics mandatory="1">808988720</G3PP-Charging-Characteristics>
         <G3PP-SGSN-MCC-MNC mandatory="1">26098</G3PP-SGSN-MCC-MNC>
         <Charging-Rule-Base-Name mandatory="1">REGULAR</Charging-Rule-Base-Name>
         <PDP-Context-Type mandatory="1">0</PDP-Context-Type>
<!--         <G3PP-User-Location-Info mandatory="1">2261066553404369</G3PP-User-Location-Info> -->
         <G3PP-RAT-Type mandatory="1">0x01</G3PP-RAT-Type>
      </PS-Information>
   </Service-Information>
</message>
