<?xml version="1.0" encoding="UTF-8"?>

<message CommandCode="272" request="1">
   <Destination-Realm mandatory="1">emblacom.com</Destination-Realm>
   <Termination-Cause mandatory="1">1</Termination-Cause>
   <!--Vendor-Specific-Application-Id mandatory="1">
      <Vendor-Id mandatory="1">10415</Vendor-Id>
      <Auth-Application-Id mandatory="1">4</Auth-Application-Id>
   </Vendor-Specific-Application-Id-->
   <Subscription-Id mandatory="1">
      <Subscription-Id-Type mandatory="1">0</Subscription-Id-Type>
      <Subscription-Id-Data mandatory="1">5493512017703</Subscription-Id-Data>
   </Subscription-Id>
   <Service-Context-Id mandatory="1">32251@3gpp.org</Service-Context-Id>
   <CC-Request-Type mandatory="1">3</CC-Request-Type>
   <CC-Request-Number mandatory="1">0</CC-Request-Number>
   <Multiple-Services-Indicator mandatory="1">1</Multiple-Services-Indicator>
   <Event-Timestamp mandatory="1"/>
   <Called-Station-Id>0050</Called-Station-Id>
   <G3PP-Charging-Id mandatory="1">33554660</G3PP-Charging-Id>
   <G3PP-GPRS-Negotiated-QoS-Profile mandatory="1">99-13921f73966897442a6868</G3PP-GPRS-Negotiated-QoS-Profile>
   <G3PP-Charging-Characteristics mandatory="1">808988720</G3PP-Charging-Characteristics>
   <G3PP-PDP-Type mandatory="1">0</G3PP-PDP-Type>
   <G3PP-SGSN-MCC-MNC mandatory="1">26098</G3PP-SGSN-MCC-MNC>
   <G3PP-GGSN-MCC-MNC mandatory="1">26006</G3PP-GGSN-MCC-MNC>
   <G3PP-NSAPI mandatory="1">5</G3PP-NSAPI>
   <G3PP-Selection-Mode mandatory="1">0</G3PP-Selection-Mode>
   <G3PP-SGSN-Address mandatory="1">ip:70.30.65.9</G3PP-SGSN-Address>
   <G3PP-GGSN-Address mandatory="1">ip:70.30.65.9</G3PP-GGSN-Address>
   <G3PP-CG-Address mandatory="1">ip:70.30.65.9</G3PP-CG-Address>
   <!--Framed-IP-Address>0xaa33fc50</Framed-IP-Address-->
   <Nokia-Rulebase-Id>CHARGE-ALL</Nokia-Rulebase-Id>
</message>
